import 'package:flutter/material.dart';

import 'event_models.dart';

const List<EventDetailData> kEventSeedData = <EventDetailData>[
  EventDetailData(
    id: 'evt_antwerp_jazz_2026',
    title: 'Antwerp Jazz Nights 2026',
    category: 'Muziek',
    categoryKey: EventCategoryKey.music,
    dateTimeLabel: 'Vrijdag • 19:30',
    locationName: 'Stadspark Arena',
    city: 'Antwerpen',
    address: 'Van Eycklei 1, 2018 Antwerpen, België',
    lat: 51.208186,
    lng: 4.418731,
    distanceOrStatus: '',
    gradient: <Color>[Color(0xFF2A1F08), Color(0xFF15120A)],
    sourceLabel: 'Fluxidi Curated',
  ),
  EventDetailData(
    id: 'evt_ghent_night_run_2026',
    title: 'Ghent Night Run',
    category: 'Sport',
    categoryKey: EventCategoryKey.sport,
    dateTimeLabel: 'Zaterdag • 20:30',
    locationName: 'Sport Vlaanderen Gent',
    city: 'Gent',
    address: 'Zuiderlaan 14, 9000 Gent, België',
    lat: 51.026364,
    lng: 3.703992,
    distanceOrStatus: '',
    gradient: <Color>[Color(0xFF1F1A0C), Color(0xFF100F0A)],
    sourceLabel: 'Fluxidi Curated',
  ),
  EventDetailData(
    id: 'evt_leuven_food_market_2026',
    title: 'Leuven Food & Culture Market',
    category: 'Vandaag',
    categoryKey: EventCategoryKey.food,
    dateTimeLabel: 'Vandaag • 17:00',
    locationName: 'Grote Markt Leuven',
    city: 'Leuven',
    address: 'Grote Markt 1, 3000 Leuven, België',
    lat: 50.879842,
    lng: 4.700517,
    distanceOrStatus: 'Actief',
    gradient: <Color>[Color(0xFF2E220B), Color(0xFF141108)],
    sourceLabel: 'Fluxidi Curated',
  ),
  EventDetailData(
    id: 'evt_barcelona_sonar_2026',
    title: 'Barcelona Sonar Weekender',
    category: 'Muziek',
    categoryKey: EventCategoryKey.music,
    dateTimeLabel: 'Vrijdag • 21:00',
    locationName: 'Fira Barcelona Gran Via',
    city: 'Barcelona',
    address: 'Av. Joan Carles I, 64, 08908 L Hospitalet de Llobregat, Spanje',
    lat: 41.354780,
    lng: 2.126349,
    distanceOrStatus: 'Internationaal',
    gradient: <Color>[Color(0xFF311E0D), Color(0xFF160E08)],
    sourceLabel: 'Fluxidi Curated',
  ),
];
