import 'hotel_model.dart';

/// Customer-safe approved stays for Fluxidi Hotels/B&B default catalog.
///
/// Notes:
/// - Only approved assets are used for visuals (no seed image refs).
/// - Records are marked as real/approved so they pass
///   `_isApprovedCustomerFacingStay`.
const List<HotelStay> kApprovedBelgiumHotelData = <HotelStay>[
  HotelStay(
    id: 'approved-warwick-brussels',
    name: 'Warwick Brussels',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Rue Duquesnoy 5, 1000 Brussels, Belgium',
    description: 'Centraal verblijf op wandelafstand van de Grote Markt.',
    imageRef: 'approved_asset:assets/fluxidi/customer_home_business_banner.png',
    lat: 50.8450,
    lng: 4.3543,
    provider: 'approved-local',
    providerType: HotelStayProviderType.localApproved,
    source: 'approved_local',
    sourceId: 'approved-warwick-brussels',
    priceHint: 'Vanaf €145',
    rating: 4.3,
    tags: <String>['city', 'business', 'brussels'],
    isRealApproved: true,
  ),
  HotelStay(
    id: 'approved-hoxton-brussels',
    name: 'The Hoxton, Brussels',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Square Victoria Regina 1, 1210 Brussels, Belgium',
    description: 'Designhotel met vlotte verbinding naar centrum en events.',
    imageRef: 'approved_asset:assets/fluxidi/customer_home_hotel_bb_banner.png',
    lat: 50.8560,
    lng: 4.3655,
    provider: 'approved-local',
    providerType: HotelStayProviderType.localApproved,
    source: 'approved_local',
    sourceId: 'approved-hoxton-brussels',
    priceHint: 'Vanaf €170',
    rating: 4.5,
    tags: <String>['design', 'city', 'brussels'],
    isRealApproved: true,
  ),
  HotelStay(
    id: 'approved-begijnhof-hotel',
    name: 'Begijnhof Hotel',
    type: HotelStayType.hotel,
    city: 'Leuven',
    region: 'Vlaams-Brabant',
    country: 'Belgium',
    address: 'Tervuursevest 70, 3000 Leuven, Belgium',
    description: 'Rustige uitvalsbasis nabij historisch centrum van Leuven.',
    imageRef: 'approved_asset:assets/fluxidi/Hotel&B&B_background.png',
    lat: 50.8712,
    lng: 4.7005,
    provider: 'approved-local',
    providerType: HotelStayProviderType.localApproved,
    source: 'approved_local',
    sourceId: 'approved-begijnhof-hotel',
    priceHint: 'Vanaf €132',
    rating: 4.2,
    tags: <String>['leuven', 'historic', 'quiet'],
    isRealApproved: true,
  ),
  HotelStay(
    id: 'approved-pantone-hotel',
    name: 'PANTONE Hotel Brussels',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Place Loix 1, 1060 Brussels, Belgium',
    description: 'Kleurrijk hotel met goede bereikbaarheid naar eventzones.',
    imageRef: 'approved_asset:assets/fluxidi/customer_home_airport_banner.png',
    lat: 50.8343,
    lng: 4.3556,
    provider: 'approved-local',
    providerType: HotelStayProviderType.localApproved,
    source: 'approved_local',
    sourceId: 'approved-pantone-hotel',
    priceHint: 'Vanaf €128',
    rating: 4.1,
    tags: <String>['brussels', 'design', 'city'],
    isRealApproved: true,
  ),
];
