import 'hotel_model.dart';

const List<HotelStay> kBelgiumHotelSeedData = <HotelStay>[
  HotelStay(
    id: 'be-oudenaarde-river-hotel',
    name: 'River Schelde Hotel',
    type: HotelStayType.hotel,
    city: 'Oudenaarde',
    region: 'Vlaamse Ardennen',
    country: 'Belgium',
    address: 'Minderbroedersstraat 11, 9700 Oudenaarde',
    description:
        'Comfortabel stads hotel op wandelafstand van markt, winkels en musea.',
    imageRef: 'seed:oudenaarde_river_hotel',
    lat: 50.8506,
    lng: 3.6087,
    priceHint: 'Vanaf EUR 109',
    rating: 4.3,
    tags: <String>['centrum', 'fietsers', 'ontbijt'],
  ),
  HotelStay(
    id: 'be-ronse-hillside-bnb',
    name: 'Hillside B&B Ronse',
    type: HotelStayType.bedAndBreakfast,
    city: 'Ronse',
    region: 'Vlaamse Ardennen',
    country: 'Belgium',
    address: 'Leuzesesteenweg 44, 9600 Ronse',
    description:
        'Kleinschalige B&B met warme ontvangst en uitzicht op de heuvels.',
    imageRef: 'seed:ronse_hillside_bnb',
    lat: 50.7454,
    lng: 3.6001,
    priceHint: 'Vanaf EUR 89',
    rating: 4.6,
    tags: <String>['rustig', 'natuur', 'familie'],
  ),
  HotelStay(
    id: 'be-gent-old-port-hotel',
    name: 'Old Port Hotel Gent',
    type: HotelStayType.hotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Koopvaardijlaan 7, 9000 Gent',
    description: 'Modern business hotel met snelle verbinding naar stadskern.',
    imageRef: 'seed:gent_old_port_hotel',
    lat: 51.0543,
    lng: 3.7174,
    priceHint: 'Vanaf EUR 129',
    rating: 4.2,
    tags: <String>['business', 'parking', 'wifi'],
  ),
  HotelStay(
    id: 'be-brugge-canal-aparthotel',
    name: 'Canal View Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Brugge',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Katelijnestraat 19, 8000 Brugge',
    description:
        'Ruime studio units met kitchenette dichtbij historische kern.',
    imageRef: 'seed:brugge_canal_aparthotel',
    lat: 51.2093,
    lng: 3.2247,
    priceHint: 'Vanaf EUR 139',
    rating: 4.4,
    tags: <String>['lang verblijf', 'centrum', 'keuken'],
  ),
  HotelStay(
    id: 'be-antwerpen-diamond-guesthouse',
    name: 'Diamond District Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Lange Kievitstraat 54, 2018 Antwerpen',
    description:
        'Stijlvolle guesthouse met compacte kamers vlak bij Antwerpen-Centraal.',
    imageRef: 'seed:antwerpen_diamond_guesthouse',
    lat: 51.2172,
    lng: 4.4211,
    priceHint: 'Vanaf EUR 99',
    rating: 4.1,
    tags: <String>['station', 'citytrip', 'self check-in'],
  ),
  HotelStay(
    id: 'be-brussel-europe-hotel',
    name: 'Europe Quarter Hotel',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Wetstraat 76, 1040 Brussel',
    description:
        'Premium city hotel ideaal voor zakelijke reizigers en korte verblijven.',
    imageRef: 'seed:brussel_europe_hotel',
    lat: 50.8449,
    lng: 4.3794,
    priceHint: 'Vanaf EUR 149',
    rating: 4.5,
    tags: <String>['premium', 'business', 'late check-in'],
  ),
  HotelStay(
    id: 'be-kortrijk-river-bnb',
    name: 'Leie River B&B',
    type: HotelStayType.bedAndBreakfast,
    city: 'Kortrijk',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Handelskaai 21, 8500 Kortrijk',
    description:
        'Charmante B&B met persoonlijke service, dicht bij de Leieboorden.',
    imageRef: 'seed:kortrijk_river_bnb',
    lat: 50.8270,
    lng: 3.2640,
    priceHint: 'Vanaf EUR 94',
    rating: 4.7,
    tags: <String>['ontbijt inbegrepen', 'koppels', 'rustig'],
  ),
  HotelStay(
    id: 'be-vlaamse-ardennen-forest-guesthouse',
    name: 'Forest Edge Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Brakel',
    region: 'Vlaamse Ardennen',
    country: 'Belgium',
    address: 'Tenbossestraat 8, 9660 Brakel',
    description:
        'Gezellige guesthouse aan de rand van wandelroutes in de Vlaamse Ardennen.',
    imageRef: 'seed:vlaamse_ardennen_forest_guesthouse',
    lat: 50.7755,
    lng: 3.7632,
    priceHint: 'Vanaf EUR 84',
    rating: 4.2,
    tags: <String>['wandelen', 'natuur', 'weekend'],
  ),
  HotelStay(
    id: 'be-gent-city-aparthotel',
    name: 'City Nest Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Korenmarkt 2, 9000 Gent',
    description:
        'Flexibele aparthotel units voor citytrip of langer zakelijk verblijf.',
    imageRef: 'seed:gent_city_nest_aparthotel',
    lat: 51.0537,
    lng: 3.7253,
    priceHint: 'Vanaf EUR 132',
    rating: 4.3,
    tags: <String>['aparthotel', 'centrum', 'zakelijk'],
  ),
  HotelStay(
    id: 'be-antwerpen-harbor-aparthotel',
    name: 'Harbor Loft Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Italielei 101, 2000 Antwerpen',
    description:
        'Ruime loft units met handige self-service faciliteiten vlak bij het Eilandje.',
    imageRef: 'seed:antwerpen_harbor_loft_aparthotel',
    lat: 51.2318,
    lng: 4.4143,
    priceHint: 'Vanaf EUR 146',
    rating: 4.0,
    tags: <String>['groep', 'keuken', 'self-service'],
  ),
];
