import 'hotel_model.dart';

const List<HotelStay> kBelgiumHotelSeedData = <HotelStay>[
  HotelStay(
    id: 'be-leopold-hotel-oudenaarde',
    name: 'Leopold Hotel Oudenaarde',
    type: HotelStayType.hotel,
    city: 'Oudenaarde',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Oudenaarde, Belgium',
    description: 'Hotel in Oudenaarde.',
    imageRef: 'seed:be_leopold_hotel_oudenaarde',
    lat: 50.8449,
    lng: 3.6052,
    latitude: 50.8449,
    longitude: 3.6052,
    websiteUrl: 'https://www.leopoldhoteloudenaarde.be',
    directBookingUrl: 'https://www.leopoldhoteloudenaarde.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'leopold-hotel-oudenaarde',
    priceHint: 'Vanaf EUR 129',
    rating: 4.3,
    tags: <String>['city hotel', 'cycling', 'business'],
    travelStyles: <String>['city-break', 'cycling', 'business'],
    ambience: 'classic-city',
    popularFor: <String>['Ronde van Vlaanderen', 'weekend'],
  ),
  HotelStay(
    id: 'be-hotond-sporthotel',
    name: 'HOTOND Sporthotel',
    type: HotelStayType.hotel,
    city: 'Kluisbergen',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Kluisbergen, Belgium',
    description: 'Sporthotel in de Vlaamse Ardennen.',
    imageRef: 'seed:be_hotond_sporthotel',
    lat: 50.7787,
    lng: 3.5294,
    latitude: 50.7787,
    longitude: 3.5294,
    websiteUrl: 'https://www.hotond.be',
    directBookingUrl: 'https://www.hotond.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'hotond-sporthotel',
    priceHint: 'Vanaf EUR 118',
    rating: 4.4,
    tags: <String>['cycling', 'hiking', 'sports'],
    travelStyles: <String>['active', 'hiking', 'cycling'],
    ambience: 'outdoor-sport',
    popularFor: <String>['training camps', 'fietsweekend'],
  ),
  HotelStay(
    id: 'be-la-pomme-dor-ronse',
    name: 'Hostellerie La Pomme d\'Or',
    type: HotelStayType.hotel,
    city: 'Ronse',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Ronse, Belgium',
    description: 'Hotel in Ronse.',
    imageRef: 'seed:be_la_pomme_dor_ronse',
    lat: 50.7445,
    lng: 3.6011,
    latitude: 50.7445,
    longitude: 3.6011,
    websiteUrl: 'https://www.lapommedor.be',
    directBookingUrl: 'https://www.lapommedor.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'hostellerie-la-pomme-dor-ronse',
    priceHint: 'Vanaf EUR 99',
    rating: 4.1,
    tags: <String>['city hotel', 'vlaamse ardennen', 'short stay'],
    travelStyles: <String>['city-break', 'slow travel'],
    ambience: 'traditional-hotel',
    popularFor: <String>['weekend', 'fietsen'],
  ),
  HotelStay(
    id: 'be-pillows-reylof-ghent',
    name: 'Pillows Grand Boutique Hotel Reylof Ghent',
    type: HotelStayType.hotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Gent, Belgium',
    description: 'Hotel in Gent.',
    imageRef: 'seed:be_pillows_reylof_ghent',
    lat: 51.0563,
    lng: 3.7168,
    latitude: 51.0563,
    longitude: 3.7168,
    websiteUrl: 'https://www.pillowshotels.com/ghent/hotel-reylof/',
    directBookingUrl: 'https://www.pillowshotels.com/ghent/hotel-reylof/',
    provider: 'direct',
    source: 'curated',
    sourceId: 'pillows-grand-boutique-hotel-reylof-ghent',
    priceHint: 'Vanaf EUR 199',
    rating: 4.7,
    tags: <String>['boutique hotel', 'wellness', 'city hotel'],
    travelStyles: <String>['premium', 'city-break', 'couples'],
    ambience: 'heritage-boutique',
    popularFor: <String>['citytrip', 'romantic stay'],
  ),
  HotelStay(
    id: 'be-1898-the-post-ghent',
    name: '1898 The Post',
    type: HotelStayType.hotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Gent, Belgium',
    description: 'Hotel in het centrum van Gent.',
    imageRef: 'seed:be_1898_the_post_ghent',
    lat: 51.0546,
    lng: 3.7212,
    latitude: 51.0546,
    longitude: 3.7212,
    websiteUrl: 'https://www.1898thepost.com',
    directBookingUrl: 'https://www.1898thepost.com',
    provider: 'direct',
    source: 'curated',
    sourceId: '1898-the-post-ghent',
    priceHint: 'Vanaf EUR 215',
    rating: 4.7,
    tags: <String>['boutique hotel', 'historic', 'city hotel'],
    travelStyles: <String>['city-break', 'culture', 'couples'],
    ambience: 'historic-boutique',
    popularFor: <String>['weekend', 'architecture'],
  ),
  HotelStay(
    id: 'be-dukes-palace-bruges',
    name: 'Hotel Dukes\' Palace Bruges',
    type: HotelStayType.hotel,
    city: 'Brugge',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Brugge, Belgium',
    description: 'Hotel in Brugge.',
    imageRef: 'seed:be_dukes_palace_bruges',
    lat: 51.2104,
    lng: 3.2241,
    latitude: 51.2104,
    longitude: 3.2241,
    websiteUrl: 'https://www.hoteldukespalace.com',
    directBookingUrl: 'https://www.hoteldukespalace.com',
    provider: 'direct',
    source: 'curated',
    sourceId: 'hotel-dukes-palace-bruges',
    priceHint: 'Vanaf EUR 229',
    rating: 4.8,
    tags: <String>['historic', 'luxury hotel', 'city hotel'],
    travelStyles: <String>['premium', 'city-break', 'couples'],
    ambience: 'palace-heritage',
    popularFor: <String>['bruges weekend', 'special occasion'],
  ),
  HotelStay(
    id: 'be-martins-relais-bruges',
    name: 'Martin\'s Relais',
    type: HotelStayType.hotel,
    city: 'Brugge',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Brugge, Belgium',
    description: 'Hotel aan de grachten in Brugge.',
    imageRef: 'seed:be_martins_relais_bruges',
    lat: 51.2117,
    lng: 3.2258,
    latitude: 51.2117,
    longitude: 3.2258,
    websiteUrl: 'https://www.martinshotels.com/en/hotel/martins-relais',
    directBookingUrl: 'https://www.martinshotels.com/en/hotel/martins-relais',
    provider: 'direct',
    source: 'curated',
    sourceId: 'martins-relais-bruges',
    priceHint: 'Vanaf EUR 169',
    rating: 4.4,
    tags: <String>['historic', 'canals', 'city hotel'],
    travelStyles: <String>['city-break', 'culture', 'couples'],
    ambience: 'canal-heritage',
    popularFor: <String>['citytrip', 'weekend'],
  ),
  HotelStay(
    id: 'be-hotel-julien-antwerp',
    name: 'Hotel Julien',
    type: HotelStayType.hotel,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Antwerpen, Belgium',
    description: 'Hotel in het centrum van Antwerpen.',
    imageRef: 'seed:be_hotel_julien_antwerp',
    lat: 51.2203,
    lng: 4.4018,
    latitude: 51.2203,
    longitude: 4.4018,
    websiteUrl: 'https://www.hotel-julien.com',
    directBookingUrl: 'https://www.hotel-julien.com',
    provider: 'direct',
    source: 'curated',
    sourceId: 'hotel-julien-antwerp',
    priceHint: 'Vanaf EUR 185',
    rating: 4.6,
    tags: <String>['boutique hotel', 'city hotel', 'design'],
    travelStyles: <String>['city-break', 'design', 'couples'],
    ambience: 'minimal-boutique',
    popularFor: <String>['weekend antwerpen', 'shopping'],
  ),
  HotelStay(
    id: 'be-radisson-blu-antwerp-city-centre',
    name: 'Radisson Blu Hotel, Antwerp City Centre',
    type: HotelStayType.hotel,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Antwerpen, Belgium',
    description: 'Hotel bij Antwerpen-Centraal.',
    imageRef: 'seed:be_radisson_blu_antwerp_city_centre',
    lat: 51.2172,
    lng: 4.4212,
    latitude: 51.2172,
    longitude: 4.4212,
    websiteUrl:
        'https://www.radissonhotels.com/en-us/hotels/radisson-blu-antwerp-city-centre',
    directBookingUrl:
        'https://www.radissonhotels.com/en-us/hotels/radisson-blu-antwerp-city-centre',
    provider: 'direct',
    source: 'curated',
    sourceId: 'radisson-blu-antwerp-city-centre',
    priceHint: 'Vanaf EUR 159',
    rating: 4.2,
    tags: <String>['city hotel', 'business', 'station'],
    travelStyles: <String>['business', 'city-break', 'family'],
    ambience: 'modern-business',
    popularFor: <String>['business trip', 'short stay'],
  ),
  HotelStay(
    id: 'be-the-hoxton-brussels',
    name: 'The Hoxton, Brussels',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Brussel, Belgium',
    description: 'Hotel in Brussel.',
    imageRef: 'seed:be_the_hoxton_brussels',
    lat: 50.8556,
    lng: 4.3618,
    latitude: 50.8556,
    longitude: 4.3618,
    websiteUrl: 'https://thehoxton.com/brussels/',
    directBookingUrl: 'https://thehoxton.com/brussels/',
    provider: 'direct',
    source: 'curated',
    sourceId: 'the-hoxton-brussels',
    priceHint: 'Vanaf EUR 169',
    rating: 4.5,
    tags: <String>['city hotel', 'design', 'coworking'],
    travelStyles: <String>['city-break', 'business', 'design'],
    ambience: 'urban-creative',
    popularFor: <String>['work trip', 'city weekend'],
  ),
  HotelStay(
    id: 'be-warwick-brussels',
    name: 'Warwick Brussels',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Brussel, Belgium',
    description: 'Hotel nabij de Grote Markt.',
    imageRef: 'seed:be_warwick_brussels',
    lat: 50.8458,
    lng: 4.3557,
    latitude: 50.8458,
    longitude: 4.3557,
    websiteUrl: 'https://www.warwickhotels.com/warwick-brussels',
    directBookingUrl: 'https://www.warwickhotels.com/warwick-brussels',
    provider: 'direct',
    source: 'curated',
    sourceId: 'warwick-brussels',
    priceHint: 'Vanaf EUR 172',
    rating: 4.3,
    tags: <String>['city hotel', 'business', 'historic center'],
    travelStyles: <String>['business', 'city-break', 'couples'],
    ambience: 'classic-grand',
    popularFor: <String>['city center stay', 'weekend'],
  ),
  HotelStay(
    id: 'be-parkhotel-kortrijk',
    name: 'Parkhotel Kortrijk',
    type: HotelStayType.hotel,
    city: 'Kortrijk',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Kortrijk, Belgium',
    description: 'Hotel in Kortrijk.',
    imageRef: 'seed:be_parkhotel_kortrijk',
    lat: 50.8248,
    lng: 3.2669,
    latitude: 50.8248,
    longitude: 3.2669,
    websiteUrl: 'https://www.parkhotel.be',
    directBookingUrl: 'https://www.parkhotel.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'parkhotel-kortrijk',
    priceHint: 'Vanaf EUR 149',
    rating: 4.4,
    tags: <String>['city hotel', 'wellness', 'business'],
    travelStyles: <String>['business', 'city-break', 'wellness'],
    ambience: 'modern-comfort',
    popularFor: <String>['expo visit', 'weekend'],
  ),
  HotelStay(
    id: 'be-hotel-messeyne-kortrijk',
    name: 'Hotel Messeyne',
    type: HotelStayType.hotel,
    city: 'Kortrijk',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Kortrijk, Belgium',
    description: 'Hotel in het centrum van Kortrijk.',
    imageRef: 'seed:be_hotel_messeyne_kortrijk',
    lat: 50.8305,
    lng: 3.2650,
    latitude: 50.8305,
    longitude: 3.2650,
    websiteUrl: 'https://www.hotelmesseyne.be',
    directBookingUrl: 'https://www.hotelmesseyne.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'hotel-messeyne-kortrijk',
    priceHint: 'Vanaf EUR 139',
    rating: 4.4,
    tags: <String>['city hotel', 'gastronomy', 'business'],
    travelStyles: <String>['city-break', 'business', 'foodie'],
    ambience: 'classic-boutique',
    popularFor: <String>['short stay', 'culinary weekend'],
  ),
  HotelStay(
    id: 'be-martins-klooster-leuven',
    name: 'Martin\'s Klooster',
    type: HotelStayType.hotel,
    city: 'Leuven',
    region: 'Vlaams-Brabant',
    country: 'Belgium',
    address: 'Leuven, Belgium',
    description: 'Hotel in Leuven.',
    imageRef: 'seed:be_martins_klooster_leuven',
    lat: 50.8799,
    lng: 4.7018,
    latitude: 50.8799,
    longitude: 4.7018,
    websiteUrl: 'https://www.martinshotels.com/en/hotel/martins-klooster',
    directBookingUrl: 'https://www.martinshotels.com/en/hotel/martins-klooster',
    provider: 'direct',
    source: 'curated',
    sourceId: 'martins-klooster-leuven',
    priceHint: 'Vanaf EUR 149',
    rating: 4.4,
    tags: <String>['historic', 'city hotel', 'business'],
    travelStyles: <String>['city-break', 'culture', 'business'],
    ambience: 'heritage-contemporary',
    popularFor: <String>['university city', 'weekend'],
  ),
  HotelStay(
    id: 'be-begijnhof-hotel-leuven',
    name: 'Begijnhof Hotel',
    type: HotelStayType.hotel,
    city: 'Leuven',
    region: 'Vlaams-Brabant',
    country: 'Belgium',
    address: 'Leuven, Belgium',
    description: 'Hotel bij Groot Begijnhof Leuven.',
    imageRef: 'seed:be_begijnhof_hotel_leuven',
    lat: 50.8737,
    lng: 4.6936,
    latitude: 50.8737,
    longitude: 4.6936,
    websiteUrl: 'https://www.begijnhofhotel.be',
    directBookingUrl: 'https://www.begijnhofhotel.be',
    provider: 'direct',
    source: 'curated',
    sourceId: 'begijnhof-hotel-leuven',
    priceHint: 'Vanaf EUR 132',
    rating: 4.2,
    tags: <String>['city hotel', 'quiet area', 'business'],
    travelStyles: <String>['business', 'city-break'],
    ambience: 'quiet-city',
    popularFor: <String>['work trip', 'short city break'],
  ),
];
