import 'hotel_model.dart';

const List<HotelStay> kBelgiumHotelSeedData = <HotelStay>[
  HotelStay(
    id: 'be-oudenaarde-river-hotel',
    name: 'River Schelde Hotel',
    type: HotelStayType.hotel,
    city: 'Oudenaarde',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Minderbroedersstraat 11, 9700 Oudenaarde',
    description:
        'Comfortabel stads hotel op wandelafstand van markt, winkels en musea.',
    imageRef: 'seed:oudenaarde_river_hotel',
    lat: 50.8506,
    lng: 3.6087,
    priceHint: 'Vanaf EUR 109',
    rating: 4.3,
    tags: <String>['city hotel', 'fietsers', 'ontbijt'],
    travelStyles: <String>['city-break', 'cycling', 'short-stay'],
    ambience: 'classic-riverside',
    popularFor: <String>['Ronde van Vlaanderen', 'weekend in de stad'],
  ),
  HotelStay(
    id: 'be-ronse-hillside-bnb',
    name: 'Hillside B&B Ronse',
    type: HotelStayType.bedAndBreakfast,
    city: 'Ronse',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Leuzesesteenweg 44, 9600 Ronse',
    description:
        'Kleinschalige B&B met warme ontvangst en uitzicht op de heuvels.',
    imageRef: 'seed:ronse_hillside_bnb',
    lat: 50.7454,
    lng: 3.6001,
    priceHint: 'Vanaf EUR 89',
    rating: 4.6,
    tags: <String>['ardennes b&b', 'rustig', 'natuur'],
    travelStyles: <String>['slow travel', 'hiking', 'couples'],
    ambience: 'cozy-rural',
    popularFor: <String>['wandelweekend', 'fietsweekend'],
  ),
  HotelStay(
    id: 'be-gent-old-port-hotel',
    name: 'Old Port Hotel Gent',
    type: HotelStayType.hotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Koopvaardijlaan 7, 9000 Gent',
    description: 'Modern business hotel met snelle verbinding naar stadskern.',
    imageRef: 'seed:gent_old_port_hotel',
    lat: 51.0543,
    lng: 3.7174,
    priceHint: 'Vanaf EUR 129',
    rating: 4.2,
    tags: <String>['business', 'parking', 'wifi'],
    travelStyles: <String>['business', 'city-break'],
    ambience: 'modern-urban',
    popularFor: <String>['zakelijke trips', 'midweek city'],
  ),
  HotelStay(
    id: 'be-brugge-canal-aparthotel',
    name: 'Canal View Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Brugge',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Katelijnestraat 19, 8000 Brugge',
    description:
        'Ruime studio units met kitchenette dichtbij historische kern.',
    imageRef: 'seed:brugge_canal_aparthotel',
    lat: 51.2093,
    lng: 3.2247,
    priceHint: 'Vanaf EUR 139',
    rating: 4.4,
    tags: <String>['lang verblijf', 'centrum', 'keuken'],
    travelStyles: <String>['family', 'long-stay', 'city-break'],
    ambience: 'romantic-canals',
    popularFor: <String>['Brugge citytrip', 'familieverblijf'],
  ),
  HotelStay(
    id: 'be-antwerpen-diamond-guesthouse',
    name: 'Diamond District Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Lange Kievitstraat 54, 2018 Antwerpen',
    description:
        'Stijlvolle guesthouse met compacte kamers vlak bij Antwerpen-Centraal.',
    imageRef: 'seed:antwerpen_diamond_guesthouse',
    lat: 51.2172,
    lng: 4.4211,
    priceHint: 'Vanaf EUR 99',
    rating: 4.1,
    tags: <String>['station', 'citytrip', 'self check-in'],
    travelStyles: <String>['city-break', 'solo'],
    ambience: 'compact-stylish',
    popularFor: <String>['weekend shoppen', 'concertnachten'],
  ),
  HotelStay(
    id: 'be-brussel-europe-hotel',
    name: 'Europe Quarter Hotel',
    type: HotelStayType.hotel,
    city: 'Brussel',
    region: 'Brussels Hoofdstedelijk Gewest',
    country: 'Belgium',
    address: 'Wetstraat 76, 1040 Brussel',
    description:
        'Premium city hotel ideaal voor zakelijke reizigers en korte verblijven.',
    imageRef: 'seed:brussel_europe_hotel',
    lat: 50.8449,
    lng: 4.3794,
    priceHint: 'Vanaf EUR 149',
    rating: 4.5,
    tags: <String>['luxury hotel', 'premium', 'business'],
    travelStyles: <String>['business', 'premium', 'city-break'],
    ambience: 'executive-luxury',
    popularFor: <String>['EU wijk', 'high-end city stays'],
  ),
  HotelStay(
    id: 'be-kortrijk-river-bnb',
    name: 'Leie River B&B',
    type: HotelStayType.bedAndBreakfast,
    city: 'Kortrijk',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Handelskaai 21, 8500 Kortrijk',
    description:
        'Charmante B&B met persoonlijke service, dicht bij de Leieboorden.',
    imageRef: 'seed:kortrijk_river_bnb',
    lat: 50.8270,
    lng: 3.2640,
    priceHint: 'Vanaf EUR 94',
    rating: 4.7,
    tags: <String>['ontbijt inbegrepen', 'koppels', 'rustig'],
    travelStyles: <String>['couples', 'relax', 'weekend'],
    ambience: 'warm-intimate',
    popularFor: <String>['romantisch weekend', 'culinaire uitstap'],
  ),
  HotelStay(
    id: 'be-vlaamse-ardennen-forest-guesthouse',
    name: 'Forest Edge Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Brakel',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Tenbossestraat 8, 9660 Brakel',
    description:
        'Gezellige guesthouse aan de rand van wandelroutes in de Vlaamse Ardennen.',
    imageRef: 'seed:vlaamse_ardennen_forest_guesthouse',
    lat: 50.7755,
    lng: 3.7632,
    priceHint: 'Vanaf EUR 84',
    rating: 4.2,
    tags: <String>['countryside guesthouse', 'wandelen', 'natuur'],
    travelStyles: <String>['nature', 'slow travel', 'hiking'],
    ambience: 'forest-hideaway',
    popularFor: <String>['Ardennenrand', 'weekend in het groen'],
  ),
  HotelStay(
    id: 'be-gent-city-aparthotel',
    name: 'City Nest Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Gent',
    region: 'Oost-Vlaanderen',
    country: 'Belgium',
    address: 'Korenmarkt 2, 9000 Gent',
    description:
        'Flexibele aparthotel units voor citytrip of langer zakelijk verblijf.',
    imageRef: 'seed:gent_city_nest_aparthotel',
    lat: 51.0537,
    lng: 3.7253,
    priceHint: 'Vanaf EUR 132',
    rating: 4.3,
    tags: <String>['aparthotel', 'centrum', 'zakelijk'],
    travelStyles: <String>['business', 'long-stay', 'family'],
    ambience: 'sleek-functional',
    popularFor: <String>['extended stay', 'remote work'],
  ),
  HotelStay(
    id: 'be-antwerpen-harbor-aparthotel',
    name: 'Harbor Loft Aparthotel',
    type: HotelStayType.aparthotel,
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'Belgium',
    address: 'Italielei 101, 2000 Antwerpen',
    description:
        'Ruime loft units met handige self-service faciliteiten vlak bij het Eilandje.',
    imageRef: 'seed:antwerpen_harbor_loft_aparthotel',
    lat: 51.2318,
    lng: 4.4143,
    priceHint: 'Vanaf EUR 146',
    rating: 4.0,
    tags: <String>['groep', 'keuken', 'self-service'],
    travelStyles: <String>['groups', 'long-stay', 'city-break'],
    ambience: 'loft-industrial',
    popularFor: <String>['vriendengroepen', 'weekend Antwerpen'],
  ),
  HotelStay(
    id: 'be-spa-thermal-wellness-resort',
    name: 'Thermal Valley Wellness Resort',
    type: HotelStayType.hotel,
    city: 'Spa',
    region: 'Luik',
    country: 'Belgium',
    address: 'Avenue Reine Astrid 77, 4900 Spa',
    description:
        'Wellness resort met thermale faciliteiten, sauna zones en stille tuinen.',
    imageRef: 'seed:spa_thermal_wellness_resort',
    lat: 50.4905,
    lng: 5.8650,
    priceHint: 'Vanaf EUR 189',
    rating: 4.7,
    tags: <String>['wellness resort', 'spa', 'relax'],
    travelStyles: <String>['wellness', 'couples', 'premium'],
    ambience: 'serene-luxury',
    popularFor: <String>['wellness weekend', 'detox breaks'],
  ),
  HotelStay(
    id: 'be-knokke-coastal-grand-hotel',
    name: 'Coastal Grand Knokke',
    type: HotelStayType.hotel,
    city: 'Knokke-Heist',
    region: 'West-Vlaanderen',
    country: 'Belgium',
    address: 'Zeedijk-Albertstrand 41, 8300 Knokke-Heist',
    description:
        'Coastal hotel met zeezichtkamers, strandservice en gastronomisch restaurant.',
    imageRef: 'seed:knokke_coastal_grand_hotel',
    lat: 51.3517,
    lng: 3.2878,
    priceHint: 'Vanaf EUR 214',
    rating: 4.6,
    tags: <String>['coastal hotel', 'strand', 'luxury hotel'],
    travelStyles: <String>['beach', 'premium', 'couples'],
    ambience: 'coastal-elegant',
    popularFor: <String>['zomer aan zee', 'culinaire weekends'],
  ),
  HotelStay(
    id: 'nl-amsterdam-canal-boutique',
    name: 'Canal House Boutique Amsterdam',
    type: HotelStayType.hotel,
    city: 'Amsterdam',
    region: 'Noord-Holland',
    country: 'Netherlands',
    address: 'Prinsengracht 201, 1015 DT Amsterdam',
    description:
        'Boutique hotel in gerenoveerd grachtenpand met verfijnde designkamers.',
    imageRef: 'seed:amsterdam_canal_house_boutique',
    lat: 52.3767,
    lng: 4.8852,
    priceHint: 'Vanaf EUR 248',
    rating: 4.7,
    tags: <String>['boutique hotel', 'grachten', 'city hotel'],
    travelStyles: <String>['city-break', 'design', 'couples'],
    ambience: 'historic-chic',
    popularFor: <String>['museumweekend', 'romantische citytrip'],
  ),
  HotelStay(
    id: 'nl-zandvoort-sea-breeze-hotel',
    name: 'Sea Breeze Zandvoort Hotel',
    type: HotelStayType.hotel,
    city: 'Zandvoort',
    region: 'Noord-Holland',
    country: 'Netherlands',
    address: 'Boulevard Barnaart 65, 2041 JA Zandvoort',
    description: 'Licht kusthotel vlak aan het strand en de duinen.',
    imageRef: 'seed:zandvoort_sea_breeze_hotel',
    lat: 52.3713,
    lng: 4.5331,
    priceHint: 'Vanaf EUR 164',
    rating: 4.3,
    tags: <String>['coastal hotel', 'duinen', 'strand'],
    travelStyles: <String>['beach', 'family', 'weekend'],
    ambience: 'fresh-coastal',
    popularFor: <String>['strandweekend', 'zomerverblijf'],
  ),
  HotelStay(
    id: 'nl-maastricht-riverside-city',
    name: 'Maas Riverside City Hotel',
    type: HotelStayType.hotel,
    city: 'Maastricht',
    region: 'Limburg',
    country: 'Netherlands',
    address: 'Maaspromenade 12, 6211 HS Maastricht',
    description:
        'Stedelijk hotel met uitzicht op de Maas en snelle toegang tot Wyck.',
    imageRef: 'seed:maastricht_riverside_city_hotel',
    lat: 50.8510,
    lng: 5.6880,
    priceHint: 'Vanaf EUR 152',
    rating: 4.4,
    tags: <String>['city hotel', 'riverside', 'culinary'],
    travelStyles: <String>['city-break', 'foodie'],
    ambience: 'modern-elegant',
    popularFor: <String>['weekend Maastricht', 'shopping'],
  ),
  HotelStay(
    id: 'nl-domburg-dune-wellness-lodge',
    name: 'Dune Wellness Lodge',
    type: HotelStayType.guesthouse,
    city: 'Domburg',
    region: 'Zeeland',
    country: 'Netherlands',
    address: 'Badhuisweg 5, 4357 AV Domburg',
    description:
        'Rustige lodge met wellness suites tussen strand en bosrijke paden.',
    imageRef: 'seed:domburg_dune_wellness_lodge',
    lat: 51.5619,
    lng: 3.4958,
    priceHint: 'Vanaf EUR 171',
    rating: 4.5,
    tags: <String>['wellness resort', 'kust', 'rust'],
    travelStyles: <String>['wellness', 'couples', 'slow travel'],
    ambience: 'calm-nordic',
    popularFor: <String>['herstelweekend', 'zee & wellness'],
  ),
  HotelStay(
    id: 'fr-paris-grand-rive-luxe',
    name: 'Grand Rive Luxe Paris',
    type: HotelStayType.hotel,
    city: 'Parijs',
    region: 'Île-de-France',
    country: 'France',
    address: 'Quai des Grands Augustins 33, 75006 Paris',
    description:
        'Luxehotel aan de Seine met panoramische suites en high-end concierge.',
    imageRef: 'seed:paris_grand_rive_luxe',
    lat: 48.8553,
    lng: 2.3430,
    priceHint: 'Vanaf EUR 329',
    rating: 4.8,
    tags: <String>['luxury hotel', 'paris', 'river view'],
    travelStyles: <String>['luxury', 'city-break', 'couples'],
    ambience: 'grand-classic',
    popularFor: <String>['honeymoon', 'iconische citytrip'],
  ),
  HotelStay(
    id: 'fr-nice-azure-coast-hotel',
    name: 'Azure Coast Hotel Nice',
    type: HotelStayType.hotel,
    city: 'Nice',
    region: 'Provence-Alpes-Côte d\'Azur',
    country: 'France',
    address: 'Promenade des Anglais 88, 06000 Nice',
    description:
        'Helder kusthotel met rooftop pool en uitzicht op de Middellandse Zee.',
    imageRef: 'seed:nice_azure_coast_hotel',
    lat: 43.6957,
    lng: 7.2653,
    priceHint: 'Vanaf EUR 219',
    rating: 4.5,
    tags: <String>['coastal hotel', 'riviera', 'rooftop'],
    travelStyles: <String>['beach', 'premium', 'city-break'],
    ambience: 'sunny-riviera',
    popularFor: <String>['zomervakantie', 'kustweekend'],
  ),
  HotelStay(
    id: 'fr-annecy-lake-boutique',
    name: 'Lake Annecy Boutique Inn',
    type: HotelStayType.hotel,
    city: 'Annecy',
    region: 'Auvergne-Rhône-Alpes',
    country: 'France',
    address: 'Rue du Pâquier 7, 74000 Annecy',
    description:
        'Boetiekhotel nabij het meer met alpine details en rustige patio.',
    imageRef: 'seed:annecy_lake_boutique_inn',
    lat: 45.9000,
    lng: 6.1294,
    priceHint: 'Vanaf EUR 197',
    rating: 4.6,
    tags: <String>['boutique hotel', 'meer', 'alpien'],
    travelStyles: <String>['nature', 'couples', 'city-break'],
    ambience: 'alpine-boutique',
    popularFor: <String>['meeruitstap', 'romantisch weekend'],
  ),
  HotelStay(
    id: 'fr-etretat-cliff-guesthouse',
    name: 'Cliffside Étretat Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Étretat',
    region: 'Normandië',
    country: 'France',
    address: 'Rue Alphonse Karr 14, 76790 Étretat',
    description: 'Intieme guesthouse op wandelafstand van de kliffen en zee.',
    imageRef: 'seed:etretat_cliffside_guesthouse',
    lat: 49.7076,
    lng: 0.2058,
    priceHint: 'Vanaf EUR 134',
    rating: 4.4,
    tags: <String>['countryside guesthouse', 'kust', 'rust'],
    travelStyles: <String>['nature', 'slow travel'],
    ambience: 'windswept-coastal',
    popularFor: <String>['fotoreizen', 'wandelweekend'],
  ),
  HotelStay(
    id: 'de-berlin-mitte-city-grand',
    name: 'Mitte City Grand Berlin',
    type: HotelStayType.hotel,
    city: 'Berlijn',
    region: 'Berlijn',
    country: 'Germany',
    address: 'Friedrichstraße 120, 10117 Berlin',
    description:
        'Stedelijk hotel met ruime kamers, ideaal voor cultuur en business.',
    imageRef: 'seed:berlin_mitte_city_grand',
    lat: 52.5196,
    lng: 13.3899,
    priceHint: 'Vanaf EUR 182',
    rating: 4.5,
    tags: <String>['city hotel', 'business', 'culture'],
    travelStyles: <String>['city-break', 'business'],
    ambience: 'urban-contemporary',
    popularFor: <String>['museumbezoek', 'zakelijke trips'],
  ),
  HotelStay(
    id: 'de-munchen-bavarian-boutique',
    name: 'Bavarian Boutique Munich',
    type: HotelStayType.hotel,
    city: 'München',
    region: 'Beieren',
    country: 'Germany',
    address: 'Ledererstraße 21, 80331 München',
    description:
        'Boetiekhotel in het historische centrum met eigentijdse Beierse accenten.',
    imageRef: 'seed:munich_bavarian_boutique',
    lat: 48.1375,
    lng: 11.5796,
    priceHint: 'Vanaf EUR 205',
    rating: 4.6,
    tags: <String>['boutique hotel', 'old town', 'design'],
    travelStyles: <String>['city-break', 'culture', 'foodie'],
    ambience: 'heritage-modern',
    popularFor: <String>['oktoberfest', 'old town weekends'],
  ),
  HotelStay(
    id: 'de-freiburg-forest-wellness',
    name: 'Forest Wellness Retreat Freiburg',
    type: HotelStayType.hotel,
    city: 'Freiburg im Breisgau',
    region: 'Baden-Württemberg',
    country: 'Germany',
    address: 'Schlossbergstraße 38, 79098 Freiburg im Breisgau',
    description:
        'Wellnessverblijf met spa faciliteiten en toegang tot het Zwarte Woud.',
    imageRef: 'seed:freiburg_forest_wellness_retreat',
    lat: 47.9959,
    lng: 7.8522,
    priceHint: 'Vanaf EUR 193',
    rating: 4.5,
    tags: <String>['wellness resort', 'forest', 'spa'],
    travelStyles: <String>['wellness', 'nature', 'slow travel'],
    ambience: 'woodland-wellness',
    popularFor: <String>['wellness breaks', 'nature retreat'],
  ),
  HotelStay(
    id: 'de-trier-mosel-guesthouse',
    name: 'Mosel Courtyard Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Trier',
    region: 'Rijnland-Palts',
    country: 'Germany',
    address: 'Simeonstraße 61, 54290 Trier',
    description:
        'Authentieke guesthouse in historische buurt, ideaal voor wijnroutes.',
    imageRef: 'seed:trier_mosel_courtyard_guesthouse',
    lat: 49.7590,
    lng: 6.6447,
    priceHint: 'Vanaf EUR 122',
    rating: 4.3,
    tags: <String>['countryside guesthouse', 'wine', 'history'],
    travelStyles: <String>['culture', 'foodie', 'slow travel'],
    ambience: 'historic-cozy',
    popularFor: <String>['wijnregio trips', 'Romeinse erfgoedroutes'],
  ),
  HotelStay(
    id: 'uk-london-river-luxury',
    name: 'London Riverfront Luxury Hotel',
    type: HotelStayType.hotel,
    city: 'London',
    region: 'Greater London',
    country: 'United Kingdom',
    address: 'South Bank 14, London SE1 9PX',
    description: 'Luxe stadshotel met uitzicht op de Thames en premium suites.',
    imageRef: 'seed:london_riverfront_luxury_hotel',
    lat: 51.5079,
    lng: -0.1200,
    priceHint: 'Vanaf GBP 289',
    rating: 4.7,
    tags: <String>['luxury hotel', 'city hotel', 'river view'],
    travelStyles: <String>['luxury', 'city-break', 'business'],
    ambience: 'metropolitan-luxe',
    popularFor: <String>['theater breaks', 'premium city stays'],
  ),
  HotelStay(
    id: 'uk-windermere-lake-bnb',
    name: 'Lake District B&B Windermere',
    type: HotelStayType.bedAndBreakfast,
    city: 'Windermere',
    region: 'Cumbria',
    country: 'United Kingdom',
    address: 'Lake Road 63, Windermere LA23 2EQ',
    description:
        'Klassieke B&B in het Lake District met persoonlijke service en tuinzicht.',
    imageRef: 'seed:windermere_lake_district_bnb',
    lat: 54.3796,
    lng: -2.9071,
    priceHint: 'Vanaf GBP 124',
    rating: 4.6,
    tags: <String>['ardennes b&b', 'lake district', 'hiking'],
    travelStyles: <String>['nature', 'couples', 'slow travel'],
    ambience: 'country-cottage',
    popularFor: <String>['hike weekends', 'landscape getaways'],
  ),
  HotelStay(
    id: 'uk-york-heritage-boutique',
    name: 'Heritage Boutique York',
    type: HotelStayType.hotel,
    city: 'York',
    region: 'North Yorkshire',
    country: 'United Kingdom',
    address: 'Stonegate 9, York YO1 8AS',
    description: 'Boetiekhotel in een monumentaal pand vlak bij de kathedraal.',
    imageRef: 'seed:york_heritage_boutique',
    lat: 53.9602,
    lng: -1.0840,
    priceHint: 'Vanaf GBP 176',
    rating: 4.5,
    tags: <String>['boutique hotel', 'history', 'city hotel'],
    travelStyles: <String>['culture', 'city-break'],
    ambience: 'heritage-refined',
    popularFor: <String>['historische citytrip', 'weekend escapes'],
  ),
  HotelStay(
    id: 'uk-bourton-cotswold-guesthouse',
    name: 'Cotswold Meadow Guesthouse',
    type: HotelStayType.guesthouse,
    city: 'Bourton-on-the-Water',
    region: 'Gloucestershire',
    country: 'United Kingdom',
    address: 'Rissington Road 17, Bourton-on-the-Water GL54 2BN',
    description:
        'Landelijke guesthouse in Cotswold stijl met rustige binnentuin.',
    imageRef: 'seed:bourton_cotswold_meadow_guesthouse',
    lat: 51.8860,
    lng: -1.7585,
    priceHint: 'Vanaf GBP 139',
    rating: 4.4,
    tags: <String>['countryside guesthouse', 'villages', 'quiet'],
    travelStyles: <String>['slow travel', 'nature', 'couples'],
    ambience: 'pastoral-cozy',
    popularFor: <String>['Cotswolds roadtrip', 'rustige retreats'],
  ),
  HotelStay(
    id: 'es-barcelona-rambla-boutique',
    name: 'Rambla Boutique Barcelona',
    type: HotelStayType.hotel,
    city: 'Barcelona',
    region: 'Catalonië',
    country: 'Spain',
    address: 'La Rambla 122, 08002 Barcelona',
    description: 'Stijlvol boutique city hotel met rooftop terras en tapasbar.',
    imageRef: 'seed:barcelona_rambla_boutique',
    lat: 41.3842,
    lng: 2.1736,
    priceHint: 'Vanaf EUR 211',
    rating: 4.6,
    tags: <String>['boutique hotel', 'city hotel', 'rooftop'],
    travelStyles: <String>['city-break', 'foodie', 'couples'],
    ambience: 'vibrant-design',
    popularFor: <String>['stedenvakantie', 'gastronomie'],
  ),
  HotelStay(
    id: 'es-marbella-coast-luxury',
    name: 'Costa del Sol Luxury Marbella',
    type: HotelStayType.hotel,
    city: 'Marbella',
    region: 'Andalusië',
    country: 'Spain',
    address: 'Paseo Marítimo 29, 29602 Marbella',
    description: 'Luxehotel aan zee met beach club en mediterrane suites.',
    imageRef: 'seed:marbella_costa_del_sol_luxury',
    lat: 36.5102,
    lng: -4.8856,
    priceHint: 'Vanaf EUR 276',
    rating: 4.7,
    tags: <String>['luxury hotel', 'coastal hotel', 'beach club'],
    travelStyles: <String>['luxury', 'beach', 'resort'],
    ambience: 'sunset-luxe',
    popularFor: <String>['zomerluxe', 'strandvakantie'],
  ),
  HotelStay(
    id: 'es-palma-harbor-city-hotel',
    name: 'Palma Harbor City Hotel',
    type: HotelStayType.hotel,
    city: 'Palma de Mallorca',
    region: 'Balearic Islands',
    country: 'Spain',
    address: 'Passeig Marítim 41, 07014 Palma',
    description:
        'City hotel met zeehavenzicht, dichtbij oude stad en maritieme clubs.',
    imageRef: 'seed:palma_harbor_city_hotel',
    lat: 39.5674,
    lng: 2.6381,
    priceHint: 'Vanaf EUR 194',
    rating: 4.4,
    tags: <String>['city hotel', 'balearic', 'harbor'],
    travelStyles: <String>['city-break', 'beach', 'couples'],
    ambience: 'mediterranean-urban',
    popularFor: <String>['eiland citytrip', 'voor- en naseizoen'],
  ),
  HotelStay(
    id: 'es-ronda-mountain-guesthouse',
    name: 'Serranía Guesthouse Ronda',
    type: HotelStayType.guesthouse,
    city: 'Ronda',
    region: 'Andalusië',
    country: 'Spain',
    address: 'Calle Armiñán 8, 29400 Ronda',
    description:
        'Kleinschalige guesthouse met uitzicht op de kloof en berglandschap.',
    imageRef: 'seed:ronda_serrania_guesthouse',
    lat: 36.7420,
    lng: -5.1670,
    priceHint: 'Vanaf EUR 118',
    rating: 4.5,
    tags: <String>['countryside guesthouse', 'mountains', 'quiet'],
    travelStyles: <String>['nature', 'slow travel', 'roadtrip'],
    ambience: 'rustic-scenic',
    popularFor: <String>['bergwandelingen', 'fotolocaties'],
  ),
];
