name: fluxidi_tracking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # === Fluxidi tracking dependencies ===
  geolocator: ^12.0.0
  http: ^1.2.2
  http_parser: ^4.1.2
  permission_handler: ^11.3.1

  # === Mapbox (official) ===
  mapbox_maps_flutter: ^2.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  mobile_scanner:
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.0.2
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  app_links: ^6.4.1
  flutter_email_sender: ^6.0.3
  file_picker: ^11.0.2
  open_filex: ^4.7.0
  flutter_secure_storage: ^10.1.0
  crypto: ^3.0.7
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fluxidi/
    - assets/Corporate BLEU Compagny/
    - assets/Clean & Professional Compagny/
    - assets/Emerald_Ivory_Company/
    - assets/events/categories/
    - assets/payment/png/
