// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.fluxidi.tracking.nativefollow

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Discrete outcomes for a single `submitNavigationPose` call.
 *
 * The Dart controller uses [NativeFollowSubmitOutcome] to update the
 * bounded `submitted / accepted / coalesced / rejected` diagnostic
 * counters. No coordinates cross the wire in either direction beyond the
 * pose itself.
 */
enum class NativeFollowSubmitOutcome(val raw: Int) {
  /**
   * Pose was accepted by the custom `LocationProvider` and forwarded to the
   * Mapbox location component (and via `FollowPuck` to the camera).
   */
  ACCEPTED(0),
  /**
   * A newer pose was in-flight or already latched; the pose was dropped
   * intentionally as a latest-wins coalesce (not a failure).
   */
  COALESCED(1),
  /** `mapInstanceId` is not currently registered in the MapView registry. */
  REJECTED_UNKNOWN_MAP(2),
  /**
   * The pose's `routeGeneration` is older than the currently-latched
   * generation.
   */
  REJECTED_STALE_GENERATION(3),
  /**
   * The pose failed a non-negotiable validity check (NaN, out-of-range lat/
   * lon, negative accuracy, non-finite timestamp).
   */
  REJECTED_INVALID_POSE(4),
  /** Native follow is disabled for this `mapInstanceId`. */
  REJECTED_NOT_ENABLED(5);

  companion object {
    fun ofRaw(raw: Int): NativeFollowSubmitOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Discrete high-level lifecycle transitions of the native custom
 * `LocationProvider` for one map instance.
 */
enum class NativeFollowProviderLifecycle(val raw: Int) {
  /**
   * A custom provider was installed on the exact MapView associated with
   * [mapInstanceId] and the map's location component now consumes Fluxidi
   * poses.
   */
  INSTALLED(0),
  /**
   * A custom provider was uninstalled (either by explicit
   * `setNativeFollowEnabled(false)` or by MapView disposal) and the stock
   * Mapbox provider was restored.
   */
  UNINSTALLED(1),
  /**
   * The MapView for [mapInstanceId] disappeared from the registry (weak
   * reference died or `dispose()` fired). The provider is torn down.
   */
  MAP_DISPOSED(2);

  companion object {
    fun ofRaw(raw: Int): NativeFollowProviderLifecycle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Latched follow-owner intent for one map instance. */
enum class NativeFollowOwner(val raw: Int) {
  /** FollowPuck owns the camera and the vehicle puck. */
  FOLLOW_PUCK(0),
  /**
   * A temporary explicit owner is active (manual view +/-, recenter,
   * overview, style_restore). The bridge does not touch the viewport while
   * this state is latched; Dart is expected to restore `followPuck` after
   * the temporary action completes.
   */
  TEMPORARY(1),
  /** Native follow is disabled for this map. */
  DISABLED(2);

  companion object {
    fun ofRaw(raw: Int): NativeFollowOwner? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One authoritative pose from Fluxidi's navigation engine (route-snapped
 * display point + smoothed course + measured speed + accuracy). Only bounded
 * scalars cross the wire; no coordinate strings, no route geometry.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeFollowPose (
  /**
   * Plugin-owned map instance id (the same string mapbox_maps_flutter's
   * `channelSuffix` uses internally).
   */
  val mapInstanceId: String,
  val latitude: Double,
  val longitude: Double,
  val courseDegrees: Double,
  val speedMetersPerSecond: Double,
  val horizontalAccuracyMeters: Double,
  val timestampMillis: Long,
  val routeGeneration: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFollowPose {
      val mapInstanceId = pigeonVar_list[0] as String
      val latitude = pigeonVar_list[1] as Double
      val longitude = pigeonVar_list[2] as Double
      val courseDegrees = pigeonVar_list[3] as Double
      val speedMetersPerSecond = pigeonVar_list[4] as Double
      val horizontalAccuracyMeters = pigeonVar_list[5] as Double
      val timestampMillis = pigeonVar_list[6] as Long
      val routeGeneration = pigeonVar_list[7] as Long
      return NativeFollowPose(mapInstanceId, latitude, longitude, courseDegrees, speedMetersPerSecond, horizontalAccuracyMeters, timestampMillis, routeGeneration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapInstanceId,
      latitude,
      longitude,
      courseDegrees,
      speedMetersPerSecond,
      horizontalAccuracyMeters,
      timestampMillis,
      routeGeneration,
    )
  }
}

/**
 * Viewport-shape target: zoom + pitch, plus optional edge insets when the
 * native `FollowPuckViewportState` supports padding (Mapbox 11.x does).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeFollowViewport (
  val mapInstanceId: String,
  val zoom: Double,
  val pitch: Double,
  val paddingTop: Double? = null,
  val paddingBottom: Double? = null,
  val paddingLeft: Double? = null,
  val paddingRight: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFollowViewport {
      val mapInstanceId = pigeonVar_list[0] as String
      val zoom = pigeonVar_list[1] as Double
      val pitch = pigeonVar_list[2] as Double
      val paddingTop = pigeonVar_list[3] as Double?
      val paddingBottom = pigeonVar_list[4] as Double?
      val paddingLeft = pigeonVar_list[5] as Double?
      val paddingRight = pigeonVar_list[6] as Double?
      return NativeFollowViewport(mapInstanceId, zoom, pitch, paddingTop, paddingBottom, paddingLeft, paddingRight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapInstanceId,
      zoom,
      pitch,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
    )
  }
}

/**
 * One-time vehicle preset install for the native `LocationPuck3D`. Reuses
 * the shared Fluxidi calibration source; no calibration constants are
 * re-declared on the Kotlin side.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeVehiclePreset (
  val mapInstanceId: String,
  val presetId: String,
  val assetUri: String,
  val modelScale: Double,
  val yawOffsetDegrees: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeVehiclePreset {
      val mapInstanceId = pigeonVar_list[0] as String
      val presetId = pigeonVar_list[1] as String
      val assetUri = pigeonVar_list[2] as String
      val modelScale = pigeonVar_list[3] as Double
      val yawOffsetDegrees = pigeonVar_list[4] as Double
      return NativeVehiclePreset(mapInstanceId, presetId, assetUri, modelScale, yawOffsetDegrees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapInstanceId,
      presetId,
      assetUri,
      modelScale,
      yawOffsetDegrees,
    )
  }
}

/**
 * Instantaneous diagnostics for one map's native-follow session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeFollowDiagnostics (
  val mapInstanceId: String,
  val owner: NativeFollowOwner,
  val acceptedPoseCount: Long,
  val coalescedPoseCount: Long,
  val rejectedPoseCount: Long,
  val viewportTransitionCount: Long,
  val providerInstallCount: Long,
  val providerUninstallCount: Long,
  val currentRouteGeneration: Long,
  val puckReady: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeFollowDiagnostics {
      val mapInstanceId = pigeonVar_list[0] as String
      val owner = pigeonVar_list[1] as NativeFollowOwner
      val acceptedPoseCount = pigeonVar_list[2] as Long
      val coalescedPoseCount = pigeonVar_list[3] as Long
      val rejectedPoseCount = pigeonVar_list[4] as Long
      val viewportTransitionCount = pigeonVar_list[5] as Long
      val providerInstallCount = pigeonVar_list[6] as Long
      val providerUninstallCount = pigeonVar_list[7] as Long
      val currentRouteGeneration = pigeonVar_list[8] as Long
      val puckReady = pigeonVar_list[9] as Boolean
      return NativeFollowDiagnostics(mapInstanceId, owner, acceptedPoseCount, coalescedPoseCount, rejectedPoseCount, viewportTransitionCount, providerInstallCount, providerUninstallCount, currentRouteGeneration, puckReady)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mapInstanceId,
      owner,
      acceptedPoseCount,
      coalescedPoseCount,
      rejectedPoseCount,
      viewportTransitionCount,
      providerInstallCount,
      providerUninstallCount,
      currentRouteGeneration,
      puckReady,
    )
  }
}
private open class PigeonNativeFollowPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeFollowSubmitOutcome.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeFollowProviderLifecycle.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeFollowOwner.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFollowPose.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFollowViewport.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeVehiclePreset.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeFollowDiagnostics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeFollowSubmitOutcome -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is NativeFollowProviderLifecycle -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is NativeFollowOwner -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is NativeFollowPose -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeFollowViewport -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeVehiclePreset -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeFollowDiagnostics -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeFollowHostApi {
  /**
   * Enables / disables the native-follow pipeline for one map instance.
   *
   * Returns `true` if the requested state is achievable on the current
   * registration (i.e. the MapView exists and is in a valid lifecycle).
   * Returns `false` if the map id is unknown; in that case the request is
   * remembered and applied on the next `onMapViewRegistered` for the same
   * id, so start-up race conditions do not silently drop the request.
   */
  fun setNativeFollowEnabled(mapInstanceId: String, enabled: Boolean, callback: (Result<Boolean>) -> Unit)
  /**
   * Submits one route-snapped / predicted pose to the custom Mapbox
   * `LocationProvider`. Callers must rate-limit to 5-10 Hz.
   */
  fun submitNavigationPose(pose: NativeFollowPose, callback: (Result<NativeFollowSubmitOutcome>) -> Unit)
  /**
   * Updates the current `FollowPuckViewportState` zoom + pitch (+ optional
   * padding). No-op when native follow is disabled for [mapInstanceId].
   */
  fun setNativeFollowViewport(viewport: NativeFollowViewport, callback: (Result<Boolean>) -> Unit)
  /**
   * Installs / hot-swaps the `LocationPuck3D` GLB + calibration for one
   * map. Called once per active preset change from Dart; no-op if the
   * preset is byte-identical to the currently-installed one.
   */
  fun setNativeVehiclePreset(preset: NativeVehiclePreset, callback: (Result<Boolean>) -> Unit)
  /**
   * Latches a temporary owner (view +/-, recenter, overview, style_restore).
   * While `temporary` is set, the native bridge does not fight the Dart
   * camera writer; Dart is responsible for calling
   * `setNativeFollowOwner(mapInstanceId, followPuck)` to return.
   */
  fun setNativeFollowOwner(mapInstanceId: String, owner: NativeFollowOwner, callback: (Result<Boolean>) -> Unit)
  /**
   * Requests a viewport transition back to `FollowPuckViewportState` using
   * `DefaultViewportTransition`. Returns `true` when the transition is
   * scheduled; `false` when the target is already active or the map is
   * disabled / unknown.
   */
  fun transitionToFollowPuck(mapInstanceId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Snapshot of the bounded diagnostic counters for [mapInstanceId].
   * Returns `null` when the map is not registered.
   */
  fun readNativeFollowDiagnostics(mapInstanceId: String, callback: (Result<NativeFollowDiagnostics?>) -> Unit)

  companion object {
    /** The codec used by NativeFollowHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonNativeFollowPigeonCodec()
    }
    /** Sets up an instance of `NativeFollowHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeFollowHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mapInstanceIdArg = args[0] as String
            val enabledArg = args[1] as Boolean
            api.setNativeFollowEnabled(mapInstanceIdArg, enabledArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.submitNavigationPose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val poseArg = args[0] as NativeFollowPose
            api.submitNavigationPose(poseArg) { result: Result<NativeFollowSubmitOutcome> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowViewport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val viewportArg = args[0] as NativeFollowViewport
            api.setNativeFollowViewport(viewportArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeVehiclePreset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val presetArg = args[0] as NativeVehiclePreset
            api.setNativeVehiclePreset(presetArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowOwner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mapInstanceIdArg = args[0] as String
            val ownerArg = args[1] as NativeFollowOwner
            api.setNativeFollowOwner(mapInstanceIdArg, ownerArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.transitionToFollowPuck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mapInstanceIdArg = args[0] as String
            api.transitionToFollowPuck(mapInstanceIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.readNativeFollowDiagnostics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mapInstanceIdArg = args[0] as String
            api.readNativeFollowDiagnostics(mapInstanceIdArg) { result: Result<NativeFollowDiagnostics?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
