// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Discrete outcomes for a single `submitNavigationPose` call.
///
/// The Dart controller uses [NativeFollowSubmitOutcome] to update the
/// bounded `submitted / accepted / coalesced / rejected` diagnostic
/// counters. No coordinates cross the wire in either direction beyond the
/// pose itself.
enum NativeFollowSubmitOutcome {
  /// Pose was accepted by the custom `LocationProvider` and forwarded to the
  /// Mapbox location component (and via `FollowPuck` to the camera).
  accepted,
  /// A newer pose was in-flight or already latched; the pose was dropped
  /// intentionally as a latest-wins coalesce (not a failure).
  coalesced,
  /// `mapInstanceId` is not currently registered in the MapView registry.
  rejectedUnknownMap,
  /// The pose's `routeGeneration` is older than the currently-latched
  /// generation.
  rejectedStaleGeneration,
  /// The pose failed a non-negotiable validity check (NaN, out-of-range lat/
  /// lon, negative accuracy, non-finite timestamp).
  rejectedInvalidPose,
  /// Native follow is disabled for this `mapInstanceId`.
  rejectedNotEnabled,
}

/// Discrete high-level lifecycle transitions of the native custom
/// `LocationProvider` for one map instance.
enum NativeFollowProviderLifecycle {
  /// A custom provider was installed on the exact MapView associated with
  /// [mapInstanceId] and the map's location component now consumes Fluxidi
  /// poses.
  installed,
  /// A custom provider was uninstalled (either by explicit
  /// `setNativeFollowEnabled(false)` or by MapView disposal) and the stock
  /// Mapbox provider was restored.
  uninstalled,
  /// The MapView for [mapInstanceId] disappeared from the registry (weak
  /// reference died or `dispose()` fired). The provider is torn down.
  mapDisposed,
}

/// Latched follow-owner intent for one map instance.
enum NativeFollowOwner {
  /// FollowPuck owns the camera and the vehicle puck.
  followPuck,
  /// A temporary explicit owner is active (manual view +/-, recenter,
  /// overview, style_restore). The bridge does not touch the viewport while
  /// this state is latched; Dart is expected to restore `followPuck` after
  /// the temporary action completes.
  temporary,
  /// Native follow is disabled for this map.
  disabled,
}

/// One authoritative pose from Fluxidi's navigation engine (route-snapped
/// display point + smoothed course + measured speed + accuracy). Only bounded
/// scalars cross the wire; no coordinate strings, no route geometry.
class NativeFollowPose {
  NativeFollowPose({
    required this.mapInstanceId,
    required this.latitude,
    required this.longitude,
    required this.courseDegrees,
    required this.speedMetersPerSecond,
    required this.horizontalAccuracyMeters,
    required this.timestampMillis,
    required this.routeGeneration,
  });

  /// Plugin-owned map instance id (the same string mapbox_maps_flutter's
  /// `channelSuffix` uses internally).
  String mapInstanceId;

  double latitude;

  double longitude;

  double courseDegrees;

  double speedMetersPerSecond;

  double horizontalAccuracyMeters;

  int timestampMillis;

  int routeGeneration;

  Object encode() {
    return <Object?>[
      mapInstanceId,
      latitude,
      longitude,
      courseDegrees,
      speedMetersPerSecond,
      horizontalAccuracyMeters,
      timestampMillis,
      routeGeneration,
    ];
  }

  static NativeFollowPose decode(Object result) {
    result as List<Object?>;
    return NativeFollowPose(
      mapInstanceId: result[0]! as String,
      latitude: result[1]! as double,
      longitude: result[2]! as double,
      courseDegrees: result[3]! as double,
      speedMetersPerSecond: result[4]! as double,
      horizontalAccuracyMeters: result[5]! as double,
      timestampMillis: result[6]! as int,
      routeGeneration: result[7]! as int,
    );
  }
}

/// Viewport-shape target: zoom + pitch, plus optional edge insets when the
/// native `FollowPuckViewportState` supports padding (Mapbox 11.x does).
class NativeFollowViewport {
  NativeFollowViewport({
    required this.mapInstanceId,
    required this.zoom,
    required this.pitch,
    this.paddingTop,
    this.paddingBottom,
    this.paddingLeft,
    this.paddingRight,
  });

  String mapInstanceId;

  double zoom;

  double pitch;

  double? paddingTop;

  double? paddingBottom;

  double? paddingLeft;

  double? paddingRight;

  Object encode() {
    return <Object?>[
      mapInstanceId,
      zoom,
      pitch,
      paddingTop,
      paddingBottom,
      paddingLeft,
      paddingRight,
    ];
  }

  static NativeFollowViewport decode(Object result) {
    result as List<Object?>;
    return NativeFollowViewport(
      mapInstanceId: result[0]! as String,
      zoom: result[1]! as double,
      pitch: result[2]! as double,
      paddingTop: result[3] as double?,
      paddingBottom: result[4] as double?,
      paddingLeft: result[5] as double?,
      paddingRight: result[6] as double?,
    );
  }
}

/// One-time vehicle preset install for the native `LocationPuck3D`. Reuses
/// the shared Fluxidi calibration source; no calibration constants are
/// re-declared on the Kotlin side.
class NativeVehiclePreset {
  NativeVehiclePreset({
    required this.mapInstanceId,
    required this.presetId,
    required this.assetUri,
    required this.modelScale,
    required this.yawOffsetDegrees,
  });

  String mapInstanceId;

  String presetId;

  String assetUri;

  double modelScale;

  double yawOffsetDegrees;

  Object encode() {
    return <Object?>[
      mapInstanceId,
      presetId,
      assetUri,
      modelScale,
      yawOffsetDegrees,
    ];
  }

  static NativeVehiclePreset decode(Object result) {
    result as List<Object?>;
    return NativeVehiclePreset(
      mapInstanceId: result[0]! as String,
      presetId: result[1]! as String,
      assetUri: result[2]! as String,
      modelScale: result[3]! as double,
      yawOffsetDegrees: result[4]! as double,
    );
  }
}

/// Instantaneous diagnostics for one map's native-follow session.
class NativeFollowDiagnostics {
  NativeFollowDiagnostics({
    required this.mapInstanceId,
    required this.owner,
    required this.acceptedPoseCount,
    required this.coalescedPoseCount,
    required this.rejectedPoseCount,
    required this.viewportTransitionCount,
    required this.providerInstallCount,
    required this.providerUninstallCount,
    required this.currentRouteGeneration,
    required this.puckReady,
  });

  String mapInstanceId;

  NativeFollowOwner owner;

  int acceptedPoseCount;

  int coalescedPoseCount;

  int rejectedPoseCount;

  int viewportTransitionCount;

  int providerInstallCount;

  int providerUninstallCount;

  int currentRouteGeneration;

  bool puckReady;

  Object encode() {
    return <Object?>[
      mapInstanceId,
      owner,
      acceptedPoseCount,
      coalescedPoseCount,
      rejectedPoseCount,
      viewportTransitionCount,
      providerInstallCount,
      providerUninstallCount,
      currentRouteGeneration,
      puckReady,
    ];
  }

  static NativeFollowDiagnostics decode(Object result) {
    result as List<Object?>;
    return NativeFollowDiagnostics(
      mapInstanceId: result[0]! as String,
      owner: result[1]! as NativeFollowOwner,
      acceptedPoseCount: result[2]! as int,
      coalescedPoseCount: result[3]! as int,
      rejectedPoseCount: result[4]! as int,
      viewportTransitionCount: result[5]! as int,
      providerInstallCount: result[6]! as int,
      providerUninstallCount: result[7]! as int,
      currentRouteGeneration: result[8]! as int,
      puckReady: result[9]! as bool,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeFollowSubmitOutcome) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NativeFollowProviderLifecycle) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeFollowOwner) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NativeFollowPose) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NativeFollowViewport) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NativeVehiclePreset) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is NativeFollowDiagnostics) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeFollowSubmitOutcome.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeFollowProviderLifecycle.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NativeFollowOwner.values[value];
      case 132:
        return NativeFollowPose.decode(readValue(buffer)!);
      case 133:
        return NativeFollowViewport.decode(readValue(buffer)!);
      case 134:
        return NativeVehiclePreset.decode(readValue(buffer)!);
      case 135:
        return NativeFollowDiagnostics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeFollowHostApi {
  /// Constructor for [NativeFollowHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeFollowHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Enables / disables the native-follow pipeline for one map instance.
  ///
  /// Returns `true` if the requested state is achievable on the current
  /// registration (i.e. the MapView exists and is in a valid lifecycle).
  /// Returns `false` if the map id is unknown; in that case the request is
  /// remembered and applied on the next `onMapViewRegistered` for the same
  /// id, so start-up race conditions do not silently drop the request.
  Future<bool> setNativeFollowEnabled(String mapInstanceId, bool enabled) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mapInstanceId, enabled]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Submits one route-snapped / predicted pose to the custom Mapbox
  /// `LocationProvider`. Callers must rate-limit to 5-10 Hz.
  Future<NativeFollowSubmitOutcome> submitNavigationPose(NativeFollowPose pose) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.submitNavigationPose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[pose]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NativeFollowSubmitOutcome?)!;
    }
  }

  /// Updates the current `FollowPuckViewportState` zoom + pitch (+ optional
  /// padding). No-op when native follow is disabled for [mapInstanceId].
  Future<bool> setNativeFollowViewport(NativeFollowViewport viewport) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowViewport$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[viewport]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Installs / hot-swaps the `LocationPuck3D` GLB + calibration for one
  /// map. Called once per active preset change from Dart; no-op if the
  /// preset is byte-identical to the currently-installed one.
  Future<bool> setNativeVehiclePreset(NativeVehiclePreset preset) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeVehiclePreset$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[preset]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Latches a temporary owner (view +/-, recenter, overview, style_restore).
  /// While `temporary` is set, the native bridge does not fight the Dart
  /// camera writer; Dart is responsible for calling
  /// `setNativeFollowOwner(mapInstanceId, followPuck)` to return.
  Future<bool> setNativeFollowOwner(String mapInstanceId, NativeFollowOwner owner) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.setNativeFollowOwner$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mapInstanceId, owner]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Requests a viewport transition back to `FollowPuckViewportState` using
  /// `DefaultViewportTransition`. Returns `true` when the transition is
  /// scheduled; `false` when the target is already active or the map is
  /// disabled / unknown.
  Future<bool> transitionToFollowPuck(String mapInstanceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.transitionToFollowPuck$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mapInstanceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Snapshot of the bounded diagnostic counters for [mapInstanceId].
  /// Returns `null` when the map is not registered.
  Future<NativeFollowDiagnostics?> readNativeFollowDiagnostics(String mapInstanceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.fluxidi_tracking.NativeFollowHostApi.readNativeFollowDiagnostics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[mapInstanceId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as NativeFollowDiagnostics?);
    }
  }
}
