import 'dart:io';

class _AirportRow {
  _AirportRow({
    required this.iata,
    required this.icao,
    required this.name,
    required this.countryCode,
    required this.countryName,
    required this.municipality,
    required this.type,
    required this.latitude,
    required this.longitude,
    required this.preciseAddress,
    required this.originalIndex,
  });

  final String iata;
  final String icao;
  final String name;
  final String countryCode;
  final String countryName;
  final String municipality;
  final String type;
  final double latitude;
  final double longitude;
  final String preciseAddress;
  final int originalIndex;
}

const _inputPath = 'tool/airport_data/airports.csv';
const _outputPath = 'lib/airport/airport_catalog.generated.dart';

void main() {
  final inputFile = File(_inputPath);
  if (!inputFile.existsSync()) {
    stderr.writeln('Input CSV not found: $_inputPath');
    exitCode = 2;
    return;
  }

  final lines = inputFile.readAsLinesSync();
  if (lines.isEmpty) {
    stderr.writeln('Input CSV is empty: $_inputPath');
    exitCode = 2;
    return;
  }

  final header = _parseCsvLine(lines.first);
  final byHeader = <String, int>{};
  for (var i = 0; i < header.length; i++) {
    byHeader[header[i]] = i;
  }

  String readCell(List<String> row, String key) {
    final idx = byHeader[key];
    if (idx == null || idx < 0 || idx >= row.length) return '';
    return row[idx].trim();
  }

  final selectedByIata = <String, _AirportRow>{};
  var rawAccepted = 0;
  for (var lineIndex = 1; lineIndex < lines.length; lineIndex++) {
    final line = lines[lineIndex];
    if (line.trim().isEmpty) {
      continue;
    }
    final row = _parseCsvLine(line);

    final iata = readCell(row, 'iata_code').toUpperCase();
    if (iata.length != 3) {
      continue;
    }

    final scheduledRaw = readCell(row, 'scheduled_service').toLowerCase();
    if (!_isScheduledServiceYes(scheduledRaw)) {
      continue;
    }

    final type = readCell(row, 'type').toLowerCase();
    if (type != 'large_airport' && type != 'medium_airport') {
      continue;
    }

    final latitude = double.tryParse(readCell(row, 'latitude_deg'));
    final longitude = double.tryParse(readCell(row, 'longitude_deg'));
    if (!_isValidCoordinatePair(latitude, longitude)) {
      continue;
    }

    final name = readCell(row, 'name');
    final countryCode = readCell(row, 'iso_country').toUpperCase();
    final countryName = readCell(row, 'country_name');
    final municipality = readCell(row, 'municipality');
    final icao = readCell(row, 'icao_code').toUpperCase();
    final preciseAddress = _buildPreciseAddress(
      name: name,
      municipality: municipality,
      countryName: countryName,
    );
    final candidate = _AirportRow(
      iata: iata,
      icao: icao,
      name: name,
      countryCode: countryCode,
      countryName: countryName,
      municipality: municipality,
      type: type,
      latitude: latitude!,
      longitude: longitude!,
      preciseAddress: preciseAddress,
      originalIndex: lineIndex,
    );

    final existing = selectedByIata[iata];
    if (existing == null || _shouldReplace(existing, candidate)) {
      selectedByIata[iata] = candidate;
    }
    rawAccepted++;
  }

  final rows = selectedByIata.values.toList(growable: false);
  final indexed = rows.indexed.toList(growable: false);
  indexed.sort((a, b) {
    int cmp(String x, String y) => x.toLowerCase().compareTo(y.toLowerCase());
    final c1 = cmp(a.$2.countryName, b.$2.countryName);
    if (c1 != 0) return c1;
    final c2 = cmp(a.$2.municipality, b.$2.municipality);
    if (c2 != 0) return c2;
    final c3 = cmp(a.$2.name, b.$2.name);
    if (c3 != 0) return c3;
    final c4 = cmp(a.$2.iata, b.$2.iata);
    if (c4 != 0) return c4;
    return a.$2.originalIndex.compareTo(b.$2.originalIndex);
  });
  final sortedRows = indexed.map((e) => e.$2).toList(growable: false);

  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/generate_airport_catalog.dart')
    ..writeln()
    ..writeln('class AirportCatalogEntry {')
    ..writeln('  const AirportCatalogEntry({')
    ..writeln('    required this.iata,')
    ..writeln('    required this.icao,')
    ..writeln('    required this.name,')
    ..writeln('    required this.countryCode,')
    ..writeln('    required this.countryName,')
    ..writeln('    required this.municipality,')
    ..writeln('    required this.type,')
    ..writeln('    required this.latitude,')
    ..writeln('    required this.longitude,')
    ..writeln('    required this.preciseAddress,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String iata;')
    ..writeln('  final String icao;')
    ..writeln('  final String name;')
    ..writeln('  final String countryCode;')
    ..writeln('  final String countryName;')
    ..writeln('  final String municipality;')
    ..writeln('  final String type;')
    ..writeln('  final double latitude;')
    ..writeln('  final double longitude;')
    ..writeln('  final String preciseAddress;')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'const List<AirportCatalogEntry> kAirportCatalog = <AirportCatalogEntry>[',
    );

  for (final row in sortedRows) {
    out
      ..writeln('  AirportCatalogEntry(')
      ..writeln("    iata: '${_escapeDart(row.iata)}',")
      ..writeln("    icao: '${_escapeDart(row.icao)}',")
      ..writeln("    name: '${_escapeDart(row.name)}',")
      ..writeln("    countryCode: '${_escapeDart(row.countryCode)}',")
      ..writeln("    countryName: '${_escapeDart(row.countryName)}',")
      ..writeln("    municipality: '${_escapeDart(row.municipality)}',")
      ..writeln("    type: '${_escapeDart(row.type)}',")
      ..writeln('    latitude: ${row.latitude.toStringAsFixed(6)},')
      ..writeln('    longitude: ${row.longitude.toStringAsFixed(6)},')
      ..writeln("    preciseAddress: '${_escapeDart(row.preciseAddress)}',")
      ..writeln('  ),');
  }
  out.writeln('];');

  final outputFile = File(_outputPath);
  outputFile.createSync(recursive: true);
  outputFile.writeAsStringSync(out.toString());

  stdout.writeln(
    'Generated ${sortedRows.length} airports from $rawAccepted matching rows -> $_outputPath',
  );
}

bool _isScheduledServiceYes(String raw) {
  final value = raw.trim().toLowerCase();
  return value == 'yes' || value == '1' || value == 'true';
}

bool _isValidCoordinatePair(double? lat, double? lng) {
  if (lat == null || lng == null) return false;
  if (!lat.isFinite || !lng.isFinite) return false;
  if (lat < -90 || lat > 90) return false;
  if (lng < -180 || lng > 180) return false;
  return true;
}

bool _shouldReplace(_AirportRow existing, _AirportRow candidate) {
  final existingLarge = existing.type == 'large_airport';
  final candidateLarge = candidate.type == 'large_airport';
  if (candidateLarge && !existingLarge) return true;
  if (existingLarge && !candidateLarge) return false;
  return candidate.originalIndex < existing.originalIndex;
}

String _buildPreciseAddress({
  required String name,
  required String municipality,
  required String countryName,
}) {
  final parts = <String>[];
  void add(String value) {
    final v = value.trim();
    if (v.isEmpty) return;
    if (parts.any((p) => p.toLowerCase() == v.toLowerCase())) return;
    parts.add(v);
  }

  add(name);
  add(municipality);
  add(countryName);
  return parts.join(', ');
}

String _escapeDart(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}

List<String> _parseCsvLine(String line) {
  final fields = <String>[];
  final buf = StringBuffer();
  var inQuotes = false;
  var i = 0;
  while (i < line.length) {
    final char = line[i];
    if (char == '"') {
      if (inQuotes && i + 1 < line.length && line[i + 1] == '"') {
        buf.write('"');
        i += 2;
        continue;
      }
      inQuotes = !inQuotes;
      i++;
      continue;
    }
    if (char == ',' && !inQuotes) {
      fields.add(buf.toString());
      buf.clear();
      i++;
      continue;
    }
    buf.write(char);
    i++;
  }
  fields.add(buf.toString());
  return fields;
}
