name = "fluxidi-tracking-api"
main = "fluxidi_tracking_api_worker_V2_1_with_route_index.js"
compatibility_date = "2026-04-23"

[vars]
COMPLIANCE_API_URL = "https://fluxidi-compliance-api.fluxidi.workers.dev"
BOOKING_API_URL = "https://fluxidi-booking-api.fluxidi.workers.dev"

[[services]]
binding = "COMPLIANCE_WORKER"
service = "fluxidi-compliance-api"

[[services]]
binding = "BOOKING_API"
service = "fluxidi-booking-api"

[[kv_namespaces]]
binding = "FLUXIDI_TRACKING"
id = "e457c0f51cfe44bca031250a0485b31e"

[[kv_namespaces]]
binding = "BOOKING_KV"
id = "6805da1ffefe4a3982b4c419250c59b1"
